import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/utils/providers";
import Sidebar from "@/components/Sidebar";
import  '@/styles/Layout.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children }) {
  return (
    <html lang="en">
      <body>
       <div className="flex flex-row flex-shrink-0">
        <Sidebar />
        <Providers>
          <div  className="flex-grow p-[20px]">
          {children}
          </div>
        </Providers>
        </div>
      </body>
    </html>
  );
}
